import asyncio,json,os
from playwright.async_api import async_playwright
URL="file://"+os.path.abspath(os.path.join(os.path.dirname(__file__),"..","dist","local.html"))
res=[]
def ok(name,cond,info=""): res.append(("PASS" if cond else "FAIL",name,info))
async def main():
  async with async_playwright() as p:
    b=await p.chromium.launch()
    pg=await b.new_page(viewport={"width":1119,"height":864})
    errs=[];pg.on("pageerror",lambda e:errs.append(str(e)))
    await pg.goto(URL)
    st=lambda: pg.evaluate("__sandbox.state()")
    lg=lambda: pg.evaluate("__sandbox.log()")
    s0=await st()
    # MIVA OPENER
    ok("opener plays on load",await pg.is_visible("#opener"))
    ok("opener focuses Skip and locks the welcome screen",await pg.evaluate("document.activeElement.id")=="openerSkip" and await pg.evaluate("document.querySelector('#welcome').inert"))
    await pg.click("#openerSkip"); await pg.wait_for_timeout(1200)
    ok("Skip ends opener and the walkthrough starts playing",not await pg.query_selector("#opener") and await pg.evaluate("(()=>{const v=document.querySelector('#vid');return !!v&&!v.paused&&v.currentTime>0})()"))
    ok("autoplaying walkthrough has focus on Pause",await pg.evaluate("document.activeElement.id")=="pPlay")
    await pg.keyboard.press("Escape"); await pg.wait_for_timeout(200)
    ok("closing it lands on Begin Practice, state untouched",await pg.evaluate("document.activeElement.id")=="beginBtn" and not await pg.evaluate("document.querySelector('#welcome').inert") and json.dumps(await st())==json.dumps(s0))
    p2=await b.new_page(); await p2.goto(URL); await p2.wait_for_timeout(6200)
    ok("opener ends on its own after ~5 s and the walkthrough plays",not await p2.query_selector("#opener") and await p2.evaluate("(()=>{const v=document.querySelector('#vid');return !!v&&!v.paused})()"))
    await p2.close()
    # browsers that block sound until the learner clicks: start muted, offer sound
    p3=await b.new_page()
    await p3.add_init_script("(()=>{const o=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){return this.muted?o.call(this):Promise.reject(new DOMException('blocked','NotAllowedError'))}})()")
    await p3.goto(URL); await p3.wait_for_timeout(6200)
    ok("sound blocked: plays muted with Turn on sound focused",await p3.evaluate("(()=>{const v=document.querySelector('#vid');return !!v&&!v.paused&&v.muted})()") and await p3.is_visible("#vUnmute") and await p3.evaluate("document.activeElement.id")=="vUnmute")
    await p3.click("#vUnmute"); await p3.wait_for_timeout(200)
    ok("Turn on sound unmutes and hides itself",await p3.evaluate("!document.querySelector('#vid').muted") and await p3.is_hidden("#vUnmute"))
    await p3.close()
    ok("seed: class name/section",s0["cls"]=={"name":"EDU 101","section":"Sandbox Class"})
    ok("seed: 1 protected post, 0 topics/assignments",len(s0["posts"])==1 and s0["posts"][0]["protected"] and not s0["topics"] and not s0["assignments"])
    ok("seed: owner + 2 students",len(s0["teachers"])==1 and s0["teachers"][0]["status"]=="owner" and len(s0["students"])==2)
    import re
    ok("seed: code XXX-XXX",bool(re.fullmatch(r"[A-Z2-9]{3}-[A-Z2-9]{3}",s0["classCode"])))
    ok("seed: nudge flag unset",s0["flags"]["unfiledNudgeShown"]==False)
    # walkthrough from welcome must not alter state
    await pg.click("#welcomeWatch"); await pg.wait_for_timeout(300)
    ok("walkthrough opens without autoplay",await pg.evaluate("(()=>{const v=document.querySelector('#vid');return !v||v.paused})()"))
    await pg.keyboard.press("Escape"); await pg.wait_for_timeout(200)
    ok("walkthrough closes, focus returns",await pg.evaluate("document.activeElement.id")=="welcomeWatch")
    await pg.click("#beginBtn"); await pg.wait_for_timeout(200)
    ok("Begin opens EDU 101 Stream",await pg.evaluate("document.querySelector('#tab-stream').getAttribute('aria-selected')")=="true")
    # TAB INTROS (Classroom-style feature-intro card, silent animation)
    ok("Stream intro shows on first visit",await pg.is_visible(".dlg.intro") and "Stream" in await pg.inner_text("#cdT"))
    ok("intro focuses Got it",await pg.evaluate("document.activeElement.id")=="introOk")
    ok("intro illustration has a text alternative",bool(await pg.get_attribute(".iv[role=img]","aria-label")))
    await pg.click("#introOk"); await pg.wait_for_timeout(100)
    ok("intro closes, focus returns to tab, state untouched",await pg.evaluate("document.activeElement.id")=="tab-stream" and json.dumps(await st())==json.dumps(s0))
    # STREAM
    await pg.click("#annOpen")
    ok("Post disabled when empty",await pg.is_disabled("#annPost"))
    await pg.fill("#annText","   ")
    ok("Post disabled for whitespace",await pg.is_disabled("#annPost"))
    await pg.fill("#annText","Welcome, everyone. Our first class begins on Monday.")
    await pg.click("#annPost"); await pg.wait_for_timeout(100)
    s=await st()
    ok("post appears at top as You/Just now",s["posts"][0]["author"]=="You" and s["posts"][0]["when"]=="Just now" and len(s["posts"])==2)
    await pg.fill("#annText","x") if await pg.query_selector("#annText") else None
    # second post, then delete it
    await pg.click("#annOpen"); await pg.fill("#annText","<b>Second</b> post"); await pg.click("#annPost")
    txt=await pg.inner_text(".post >> nth=0")
    ok("user text rendered safely",("<b>Second</b>" in txt) and await pg.evaluate("!document.querySelector('.post-b b')"))
    pid=(await st())["posts"][0]["id"]
    await pg.click(f'[data-post-menu="{pid}"]'); await pg.click("#mDeletePost")
    s=await st(); ok("own post removed",len(s["posts"])==2)
    await pg.click('[data-post-menu="post-welcome"]')
    items=await pg.eval_on_selector_all(".menu [role=menuitem]","els=>els.map(e=>e.textContent)")
    ok("welcome post has no delete/edit",not any("Delete" in i or "Edit" in i for i in items),str(items))
    await pg.keyboard.press("Escape")
    # edit own post
    pid=(await st())["posts"][0]["id"]
    await pg.click(f'[data-post-menu="{pid}"]'); await pg.click("#mEditPost"); await pg.fill("#editText","  ")
    ok("edit save disabled when empty",await pg.is_disabled("#editSave"))
    await pg.fill("#editText","Edited text"); await pg.click("#editSave")
    ok("post edited",(await st())["posts"][0]["text"]=="Edited text")
    # CLASSWORK
    await pg.click("#tab-classwork"); await pg.wait_for_timeout(100)
    ok("Classwork intro shows on first visit","topics" in (await pg.inner_text(".dlg.intro")).lower())
    await pg.keyboard.press("Escape"); await pg.wait_for_timeout(100)
    ok("Escape closes intro",not await pg.query_selector(".dlg.intro"))
    await pg.click("#createBtn"); await pg.click("#mTopic")
    ok("topic Add disabled when empty",await pg.is_disabled("#topicAdd"))
    await pg.fill("#topicName","   "); ok("topic Add disabled for spaces",await pg.is_disabled("#topicAdd"))
    await pg.keyboard.press("Escape"); await pg.wait_for_timeout(100)
    ok("dialog Escape returns focus to Create",await pg.evaluate("document.activeElement.id")=="createBtn")
    await pg.click("#createBtn"); await pg.click("#mTopic"); await pg.fill("#topicName","Week 1"); await pg.click("#topicAdd")
    await pg.click("#createBtn"); await pg.click("#mAssignment")
    ok("Assign disabled without title",await pg.is_disabled("#aAssign"))
    opts=await pg.eval_on_selector_all("#aTopic option","els=>els.map(e=>e.textContent)")
    ok("topic selector from state",opts==["No topic","Week 1"],str(opts))
    await pg.fill("#aTitle","Introduce yourself"); await pg.select_option("#aTopic",label="Week 1"); await pg.click("#aAssign")
    s=await st(); ok("assignment filed under Week 1",s["assignments"][0]["topicId"]==s["topics"][0]["id"])
    ok("topic count shows 1 item","1 item" in await pg.inner_text(f'[data-topic="{s["topics"][0]["id"]}"] .tcount'))
    for n in ["Loose A","Loose B"]:
        await pg.click("#createBtn"); await pg.click("#mAssignment"); await pg.fill("#aTitle",n); await pg.click("#aAssign")
        if n=="Loose A": ok("no nudge at 1 unfiled",not await pg.query_selector("#nudge"))
    ok("nudge appears at 2 unfiled",bool(await pg.query_selector("#nudge")))
    ok("nudge flag set",(await st())["flags"]["unfiledNudgeShown"]==True)
    await pg.click("#tab-stream"); await pg.click("#tab-classwork"); await pg.wait_for_timeout(100)
    ok("nudge not repeated after tab change",not await pg.query_selector("#nudge"))
    ok("intro not repeated on revisit",not await pg.query_selector(".dlg.intro"))
    await pg.click("#createBtn"); await pg.click("#mAssignment"); await pg.fill("#aTitle","Loose C"); await pg.click("#aAssign")
    ok("nudge not repeated at 3 unfiled",not await pg.query_selector("#nudge"))
    ok("No topic section lists 3","3 items" in await pg.inner_text("#h-nt + .tcount"))
    # move
    aid=[a for a in (await st())["assignments"] if a["title"]=="Loose C"][0]["id"]
    await pg.click(f'[data-item-menu="{aid}"]'); await pg.click("#mMove"); await pg.select_option("#moveTopic",label="Week 1"); await pg.click("#moveGo")
    ok("move to topic",[a for a in (await st())["assignments"] if a["id"]==aid][0]["topicId"] is not None)
    # editing an assignment and changing its topic in one commit is one logged action
    l0=await lg()
    await pg.click(f'[data-item-menu="{aid}"]'); await pg.click(".menu [role=menuitem]")
    await pg.fill("#aTitle","Loose C renamed"); await pg.select_option("#aTopic",label="No topic"); await pg.click("#aAssign")
    l1=await lg()
    ok("edit that also changes topic counts once",(l1["assignmentsEdited"]+l1["assignmentsMoved"])-(l0["assignmentsEdited"]+l0["assignmentsMoved"])==1,
       f'edited {l0["assignmentsEdited"]}->{l1["assignmentsEdited"]}, moved {l0["assignmentsMoved"]}->{l1["assignmentsMoved"]}')
    ok("summary total matches actions",[a for a in (await st())["assignments"] if a["id"]==aid][0]["topicId"] is None)
    # PEOPLE
    await pg.click("#tab-people"); await pg.wait_for_timeout(100)
    ok("People intro shows on first visit",await pg.is_visible(".dlg.intro")); await pg.click("#introOk")
    await pg.click("#inviteBtn"); await pg.fill("#invEmail","not-an-email"); await pg.click("#invSubmit")
    ok("invalid email rejected",len((await st())["teachers"])==1 and await pg.get_attribute("#invEmail","aria-invalid")=="true")
    await pg.fill("#invEmail","tutor@example.com"); await pg.click("#invSubmit")
    s=await st(); ok("co-teacher pending",s["teachers"][1]["status"]=="pending" and "Pending" in await pg.inner_text("#panel"))
    ok("owner has no remove control",await pg.evaluate("!document.querySelector('.prow .b-owner').parentElement.querySelector('[data-teacher-menu]')"))
    await pg.click("#addStudentBtn"); ok("Add student disabled when empty",await pg.is_disabled("#stuSubmit"))
    await pg.fill("#stuName","Ada Okafor"); await pg.click("#stuSubmit")
    ok("student added, headcount 3",len((await st())["students"])==3 and "3 students" in await pg.inner_text("#headcount"))
    sid=(await st())["students"][0]["id"]
    await pg.click(f'[data-student-menu="{sid}"]'); await pg.click(".menu [role=menuitem]")
    ok("student removed, headcount 2",len((await st())["students"])==2 and "2 students" in await pg.inner_text("#headcount"))
    codes=set();prev=(await st())["classCode"];same=False
    for i in range(40):
        await pg.click("#regenBtn"); c=(await st())["classCode"]; same|=(c==prev); prev=c
    ok("regenerate never repeats previous code",not same)
    # tab switching retains state
    await pg.click("#tab-stream"); ok("stream posts retained",len(await pg.query_selector_all(".post"))==2)
    # help + guide don't change state
    before=json.dumps(await st())
    await pg.click("#dHelp"); await pg.click("#hWhat"); await pg.click("#hIntro"); await pg.wait_for_timeout(100)
    ok("intro replays from Practice Help",await pg.is_visible(".dlg.intro")); await pg.click("#introOk")
    await pg.click("#dHelp"); await pg.click("#hWhat"); await pg.click("#hBack"); await pg.click("#hGuide")
    await pg.click("[data-g='0']"); await pg.wait_for_timeout(200)
    ok("guide shows spotlight on composer",await pg.evaluate("!document.querySelector('#spot').hidden"))
    await pg.click("#annOpen"); await pg.wait_for_timeout(100)
    ok("guide advanced to step 2",("step 2" in (await pg.inner_text("#coach")).lower()))
    await pg.click("#coachExit")
    ok("guide exit keeps state",json.dumps(await st())==before)
    await pg.click("#dWatch"); await pg.wait_for_timeout(200); await pg.keyboard.press("Escape")
    ok("walkthrough doesn't alter state",json.dumps(await st())==before)
    # summary
    await pg.click("#dEnd"); await pg.wait_for_timeout(200)
    t=await pg.inner_text("#summary")
    ok("summary says Not a score","Not a score" in t)
    ok("summary separates current vs actions","Your class right now" in t and "Actions you tried" in t)
    l=await lg(); ok("log counts committed actions",l["postsCreated"]==2 and l["postsRemoved"]==1 and l["topicsCreated"]==1 and l["assignmentsCreated"]==4 and l["invitesSent"]==1 and l["studentsAdded"]==1 and l["studentsRemoved"]==1,str(l))
    await pg.click("#sc-people-2"); await pg.fill("#transfer","Create topics before posting.")
    await pg.click("[data-cont='classwork']")
    ok("continue returns with state",len((await st())["assignments"])==4 and await pg.evaluate("document.querySelector('#tab-classwork').getAttribute('aria-selected')")=="true")
    await pg.click("#dEnd"); await pg.click("#sumFinish")
    ok("finish shows transfer sentence","Create topics before posting." in await pg.inner_text("#finish"))
    old=(await st())["classCode"]
    await pg.click("#finAgain"); s=await st(); l=await lg()
    ok("reset restores seed",len(s["posts"])==1 and not s["topics"] and not s["assignments"] and len(s["teachers"])==1 and len(s["students"])==2 and s["flags"]["unfiledNudgeShown"]==False and s["classCode"]!=old)
    ok("reset clears log",l["postsCreated"]==0 and l["invitesSent"]==0 and l["codeRegenerations"]==0)
    ok("no localStorage used",await pg.evaluate("localStorage.length")==0)
    ok("no JS errors",not errs,str(errs))
    await b.close()
asyncio.run(main())
for r in res: print(*r)
print(sum(r[0]=="PASS" for r in res),"/",len(res))
